version: '3.9'
services:
  server:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: on-failure
    networks:
      - my-network


networks:
  my-network:
