version: '3.9'
services:
  nginx:
    container_name: mynginx
    build: requirements/nginx
    ports:
      - 443:443
    restart: on-failure
    volumes:
      - wp:/var/www/html
    networks:
      - my-network
    depends_on:
      - wordpress

  wordpress:
    container_name: mywordpress
    build: requirements/wordpress
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb
    restart: on-failure
    networks:
      - my-network
    volumes:
      - wp:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    container_name: mymariadb
    build: 
      context: requirements/mariadb
      args:
        MYSQL_DB_NAME: ${MYSQL_DB_NAME}
        MYSQL_USER_NAME: ${MYSQL_USER_NAME}
        MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    restart: on-failure
    networks:
      - my-network
    volumes:
      - sql:/var/lib/mysql

volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      device: /home/${USERNAME}/data/wp
      o: bind
  sql:
    name: db
    driver: local
    driver_opts:
      type: none
      device: /home/${USERNAME}/data/sql
      o: bind

networks:
  my-network:
    name: docker-network

