version: '3.9'
services:
  nginx:
    container_name: mynginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    restart: on-failure
    volumes:
      - wordpress-files:/var/www/html
    networks:
      - my-network
    depends_on:
      - wordpress

  wordpress:
    container_name: mywordpress
    # image: wordpress:latest
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile  
    restart: on-failure
    networks:
      - my-network
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress-files:/var/www/html
    depends_on:
      - mariadb
    # ports:
    #   - 8001:80

  mariadb:
    container_name: mymariadb
    image: mariadb:latest
    # build:
    #   context: requirements/mariadb
    #   dockerfile: Dockerfile
    # ports:
    #   - "3306:3306"
    restart: always
    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  wordpress-files:
  wordpress-content:
  shared:
  db-data:
  

networks:
  my-network:

