version: '3.9'
services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: on-failure
    volumes:
      - wordpress-files:/var/www/html/wp-content
      # - shared:/var/www/html/shared
    networks:
      - my-network
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:latest
    # build:
    #   context: requirements/wordpress
    #   dockerfile: dockerfile
    restart: on-failure
    networks:
      - my-network
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress-files:/var/www/html/wp-content
      # - shared:/var/www/html/shared
    # expose:
    #   - "9000"
    ports:
      - 8001:80
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    # build:
    #   context: requirements/mysql
    #   dockerfile: Dockerfile
    restart: on-failure
    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  wordpress-files:
  shared:
  db-data:
  

networks:
  my-network:

