version: '3.9'
services:
  nginx:
    container_name: mynginx
    build: nginx
    ports:
      - 443:443
    restart: on-failure
    networks:
      - my-network
    volumes:
      - wp:/var/www/html
    depends_on:
      - wordpress

  wordpress:
    container_name: mywordpress
    build: wordpress
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb
    restart: on-failure
    networks:
      - my-network
    volumes:
      - wp:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    container_name: mymariadb
    build: 
      context: mariadb
      args:
        MYSQL_DB_NAME: ${MYSQL_DB_NAME}
        MYSQL_USER_NAME: ${MYSQL_USER_NAME}
        MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    restart: on-failure
    networks:
      - my-network
    volumes:
      - sql:/var/lib/mysql
  
  adminer:
    container_name: myadminer
    build: Adminer
    restart: on-failure
    networks:
      - my-network
    volumes:
      - wp:/var/www/html
    depends_on:
      - wordpress
  
  static-website:
    container_name: myportfolio
    build: StaticWebsite
    environment:
      - USERNAME=${USERNAME}
    restart: on-failure
    networks:
      - my-network
    volumes:
      - wp:/var/www/html
    depends_on:
      - wordpress

  ftp-server:
    container_name: myftp
    build: ftp
    env_file:
      - .env
    ports:
        - 20:20
        - 21:21
    restart: on-failure
    networks:
      - my-network
    volumes:
      - wp:/var/ftp/pub
    depends_on:
      - wordpress

  redis:
    container_name: myredis
    build: redis
    restart: on-failure
    networks:
      - my-network
    depends_on:
      - wordpress

  tor:
    container_name: mytor
    build: tor
    restart: on-failure
    ports:
      - "9050:9050"


volumes:
  wp:
    name: wp-b
    driver: local
    driver_opts:
      type: none
      device: /home/${USERNAME}/data/bonus/wp
      o: bind
  sql:
    name: db-b
    driver: local
    driver_opts:
      type: none
      device: /home/${USERNAME}/data/bonus/sql
      o: bind

networks:
  my-network:
    name: docker-network

